# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyFirstUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1110, 20, 71, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 20, 31, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 20, 31, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 20, 31, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(620, 20, 31, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(660, 20, 31, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(700, 20, 51, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(760, 20, 51, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(820, 20, 51, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 70, 101, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(110, 70, 721, 181))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(950, 60, 151, 51))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(1110, 60, 151, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(110, 270, 791, 141))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(1130, 610, 91, 31))
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(1130, 580, 111, 31))
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(1130, 520, 111, 31))
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        self.radioButton_4.setGeometry(QtCore.QRect(1130, 550, 111, 31))
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(Form)
        self.radioButton_5.setGeometry(QtCore.QRect(1130, 670, 111, 31))
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(Form)
        self.radioButton_6.setGeometry(QtCore.QRect(1130, 640, 131, 31))
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_4.setGeometry(QtCore.QRect(110, 420, 791, 141))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_5.setGeometry(QtCore.QRect(110, 570, 791, 141))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.verticalScrollBar = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar.setGeometry(QtCore.QRect(910, 270, 21, 441))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(950, 20, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.textBrowser_6 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_6.setGeometry(QtCore.QRect(940, 470, 331, 241))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.radioButton_7 = QtWidgets.QRadioButton(Form)
        self.radioButton_7.setGeometry(QtCore.QRect(960, 550, 111, 31))
        self.radioButton_7.setChecked(False)
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(Form)
        self.radioButton_8.setEnabled(True)
        self.radioButton_8.setGeometry(QtCore.QRect(960, 520, 111, 31))
        self.radioButton_8.setMouseTracking(True)
        self.radioButton_8.setTabletTracking(False)
        self.radioButton_8.setAcceptDrops(False)
        self.radioButton_8.setAutoFillBackground(False)
        self.radioButton_8.setChecked(False)
        self.radioButton_8.setAutoRepeat(False)
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(Form)
        self.radioButton_9.setGeometry(QtCore.QRect(960, 580, 121, 31))
        self.radioButton_9.setChecked(False)
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName("radioButton_9")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1040, 490, 131, 20))
        self.label.setObjectName("label")
        self.radioButton_10 = QtWidgets.QRadioButton(Form)
        self.radioButton_10.setGeometry(QtCore.QRect(960, 610, 131, 31))
        self.radioButton_10.setChecked(False)
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName("radioButton_10")
        self.textBrowser_7 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_7.setGeometry(QtCore.QRect(10, 280, 101, 101))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_8.setGeometry(QtCore.QRect(10, 430, 101, 101))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_9.setGeometry(QtCore.QRect(10, 580, 101, 101))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(1110, 120, 151, 51))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(950, 120, 151, 51))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(1110, 180, 151, 51))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(950, 180, 151, 51))
        self.pushButton_17.setObjectName("pushButton_17")
        self.textBrowser_10 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_10.setGeometry(QtCore.QRect(840, 70, 91, 181))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.radioButton_11 = QtWidgets.QRadioButton(Form)
        self.radioButton_11.setGeometry(QtCore.QRect(850, 110, 71, 21))
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(Form)
        self.radioButton_12.setGeometry(QtCore.QRect(850, 130, 71, 21))
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(Form)
        self.radioButton_13.setGeometry(QtCore.QRect(850, 150, 71, 21))
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(Form)
        self.radioButton_14.setGeometry(QtCore.QRect(850, 170, 71, 21))
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(Form)
        self.radioButton_15.setGeometry(QtCore.QRect(850, 190, 71, 21))
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(Form)
        self.radioButton_16.setGeometry(QtCore.QRect(850, 210, 71, 21))
        self.radioButton_16.setAutoExclusive(False)
        self.radioButton_16.setObjectName("radioButton_16")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(850, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textBrowser_15 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_15.setGeometry(QtCore.QRect(110, 10, 361, 61))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(120, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(230, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(360, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(120, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(360, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(230, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(880, 20, 51, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.textBrowser_16 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_16.setGeometry(QtCore.QRect(10, 10, 101, 61))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(940, 240, 331, 221))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_11.setGeometry(QtCore.QRect(0, 0, 151, 91))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_13.setGeometry(QtCore.QRect(160, 0, 151, 91))
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_14.setGeometry(QtCore.QRect(160, 90, 151, 91))
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_12.setGeometry(QtCore.QRect(0, 90, 151, 91))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_17.setGeometry(QtCore.QRect(0, 0, 151, 181))
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_18.setGeometry(QtCore.QRect(160, 0, 151, 181))
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.tabWidget.addTab(self.tab_2, "")
        self.radioButton_17 = QtWidgets.QRadioButton(Form)
        self.radioButton_17.setGeometry(QtCore.QRect(960, 640, 131, 31))
        self.radioButton_17.setChecked(False)
        self.radioButton_17.setAutoExclusive(False)
        self.radioButton_17.setObjectName("radioButton_17")
        self.tabWidget.raise_()
        self.textBrowser_6.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.textBrowser_3.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.radioButton_6.raise_()
        self.textBrowser_4.raise_()
        self.textBrowser_5.raise_()
        self.verticalScrollBar.raise_()
        self.comboBox.raise_()
        self.radioButton_7.raise_()
        self.radioButton_8.raise_()
        self.radioButton_9.raise_()
        self.label.raise_()
        self.radioButton_10.raise_()
        self.textBrowser_7.raise_()
        self.textBrowser_8.raise_()
        self.textBrowser_9.raise_()
        self.pushButton_12.raise_()
        self.pushButton_14.raise_()
        self.pushButton_15.raise_()
        self.pushButton_17.raise_()
        self.textBrowser_10.raise_()
        self.radioButton_11.raise_()
        self.radioButton_12.raise_()
        self.radioButton_13.raise_()
        self.radioButton_14.raise_()
        self.radioButton_15.raise_()
        self.radioButton_16.raise_()
        self.label_2.raise_()
        self.textBrowser_15.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.pushButton_13.raise_()
        self.textBrowser_16.raise_()
        self.label_9.raise_()
        self.radioButton_17.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "搜尋"))
        self.pushButton_2.setText(_translate("Form", "日"))
        self.pushButton_3.setText(_translate("Form", "周"))
        self.pushButton_4.setText(_translate("Form", "月"))
        self.pushButton_5.setText(_translate("Form", "季"))
        self.pushButton_6.setText(_translate("Form", "年"))
        self.pushButton_7.setText(_translate("Form", "縮小"))
        self.pushButton_8.setText(_translate("Form", "放大"))
        self.pushButton_9.setText(_translate("Form", "畫線"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\';\">2019/01/01</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:8pt;\">開盤價：10.00</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:8pt;\">收盤價：10.00</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:8pt;\">最高價：20.00</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:8pt;\">最低價：10.00</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\';\">漲/跌 10</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\';\">漲/跌 10.1%</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:72pt; font-weight:600; vertical-align:sub;\">蠟燭圖</span></p></body></html>"))
        self.pushButton_10.setText(_translate("Form", "條件搜尋"))
        self.pushButton_11.setText(_translate("Form", "更新資料"))
        self.radioButton.setText(_translate("Form", "MA均線"))
        self.radioButton_2.setText(_translate("Form", "KD指標"))
        self.radioButton_3.setText(_translate("Form", "RSI指標"))
        self.radioButton_4.setText(_translate("Form", "MACD指標"))
        self.radioButton_5.setText(_translate("Form", "DMI指標"))
        self.radioButton_6.setText(_translate("Form", "乖離率(BIAS)"))
        self.comboBox.setItemText(0, _translate("Form", "輸入股票名/代號"))
        self.radioButton_7.setText(_translate("Form", "成交金額"))
        self.radioButton_8.setText(_translate("Form", "成交張(股)數"))
        self.radioButton_9.setText(_translate("Form", "融資及融券數"))
        self.label.setText(_translate("Form", "選擇顯示(可複選)"))
        self.radioButton_10.setText(_translate("Form", "三法人買賣股數"))
        self.pushButton_12.setText(_translate("Form", "深度學習"))
        self.pushButton_14.setText(_translate("Form", "計算盈虧"))
        self.pushButton_15.setText(_translate("Form", "設定下載"))
        self.pushButton_17.setText(_translate("Form", "資料設定"))
        self.radioButton_11.setText(_translate("Form", "周線"))
        self.radioButton_12.setText(_translate("Form", "雙周線"))
        self.radioButton_13.setText(_translate("Form", "月線"))
        self.radioButton_14.setText(_translate("Form", "季線"))
        self.radioButton_15.setText(_translate("Form", "半年線"))
        self.radioButton_16.setText(_translate("Form", "年線"))
        self.label_2.setText(_translate("Form", "MA均線"))
        self.textBrowser_15.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'新細明體\';\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Form", "周線：00.00"))
        self.label_4.setText(_translate("Form", "雙周線：00.00"))
        self.label_5.setText(_translate("Form", "月線：00.00"))
        self.label_6.setText(_translate("Form", "季線：00.00"))
        self.label_7.setText(_translate("Form", "年線：00.00"))
        self.label_8.setText(_translate("Form", "半年線：00.00"))
        self.pushButton_13.setText(_translate("Form", "刪線"))
        self.label_9.setText(_translate("Form", "上市"))
        self.textBrowser_11.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:8pt;\">殖利率(%)：</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'新細明體\'; font-size:3.5pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:22pt; font-weight:600;\">10.1</span></p></body></html>"))
        self.textBrowser_13.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\';\">淨值比：</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'新細明體\'; font-size:3.5pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:24pt; font-weight:600;\">10.1</span></p></body></html>"))
        self.textBrowser_14.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:11pt;\">2019年 01月 01日</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'新細明體\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:11pt;\">下午</span><span style=\" font-family:\'新細明體\'; font-size:11pt; font-weight:600;\"> 1:30</span></p></body></html>"))
        self.textBrowser_12.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:8pt;\">ＥＰＳ：</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'新細明體\'; font-size:3.5pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'新細明體\'; font-size:22pt; font-weight:600;\">10.1</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "資訊"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "預測"))
        self.radioButton_17.setText(_translate("Form", "曾氏通道"))

